### PR TITLE
fixes spelling

### LINKED ISSUE #18: note that difficulty is spelt with one f in the interface
dificulty

### PR DESCRIPTION
**Pull request by tansaku**
fixes #18

### CODE REVIEW

**Comment by arreche** [comment]
I would suggest adding a test. But 👍

**Comment by tansaku** [comment]
would be good to add a test

**Comment by Zsuark** [comment]
Test added - please review

**Comment by tansaku** [comment]
passes locally for me - good test 

one concern is that many files have been touched with indentation changes - it's great to standardize on a particular indentation pattern, but it makes it harder to review the PR ...

File: test.js [hunk 1]
```diff
@@ -132,26 +132,49 @@ describe('Persistence', (done) => {
...
+      .send({
+        channel_id: '18_fix_spelling_issue channel_id',
+        text: '18_fix_spelling_issue text'
+      })
+      .end((err, res) => {
+        res.should.have.status(200)
+        res.should.be.json
+
+        const responseText = res.body.attachments[0].text
+        responseText.should.have.string('Please choose a difficulty')
```
Comment (arreche) [inline test.js]: I would suggest adding this assertion to the existing tests rather than creating new ones for fixes.

[Start a voting session](https://github.com/AgileVentures/asyncvoter-slack-command/pull/20/files#diff-1dd241c4cd3fd1dd89c570cee98b79ddR59) seems to be a good place for checking for user indications.

Comment (Zsuark) [inline test.js]: Done

File: test.js [hunk 2]
```diff
@@ -132,26 +141,27 @@ describe('Persistence', (done) => {
...
-
-      done()
-    })
   })
 
 })
 
-const pprint = (json) => JSON.stringify(json, null, '\t')
\ No newline at end of file
+// Zsuark - 20170317 - Is this pprint function ever used?
```
Comment (arreche) [inline test.js]: @Zsuark Actually this is never used.

But don't worry. We can detect and fix this kind of stuff when we'll setup a linter.
